include:
  - project: exploit/k8s/utils/k8s-deploy
    file: /.k8s-ci.yml

stages:
  - docker
  - k8s-pipeline

build:
  stage: docker
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache git make
    - make docker-registry-login
  script:
    - git describe --always --tags --first-parent
    - make docker-build
    - make docker-push-registry
  environment:
    name: integratoin
    url: http://nginx.mca.integ.ftven.net/
