image: docker:latest

stages:
  - build

variables:
  CONTAINER_LOCAL_IMAGE: nginx-vod-module
  CONTAINER_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE_NAME: mediaio/nginx-vod-module

before_script:
  - docker info

build_image:
  stage: build
  script:
    - export IMAGE_TAG=`git describe --always --tags --first-parent`
    - docker build -t $CONTAINER_LOCAL_IMAGE .
    - docker login -u maarnaud -p $REGISTRY_PASSWORD $CONTAINER_REGISTRY
    - docker tag $CONTAINER_LOCAL_IMAGE $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:$IMAGE_TAG
    - docker push $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:$IMAGE_TAG
    - echo $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:$IMAGE_TAG
  tags:
    - mediaio

